DB_URL=jdbc:mysql://localhost:3306/mybookshop?useUnicode=true&characterEncoding=utf-8
DB_DRIVER=com.mysql.jdbc.Driver
DB_USERNAME=root
DB_PASSWORD=123456

# QQ邮箱SMTP配置（需要开启QQ邮箱的POP3/SMTP服务并使用授权码）
EMAIL_HOST=smtp.qq.com
EMAIL_PORT=465
EMAIL_USER=3380958706@qq.com
EMAIL_PASS=qmaedioymbfrcibh
